name: cached_s5_video
description: Cached Video Provider for S5. Allows an application to take an S5 CID and display it with a simple, drop in, module.
repository: https://github.com/s5-dev/cached_s5_video
homepage: https://github.com/s5-dev/cached_s5_video

version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_s5_manager: ^1.2.1
  flutter:
    sdk: flutter
  flutter_thumbhash: ^0.1.0+1
  logger: ^2.4.0
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  s5: ^0.2.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

topics:
  - cache
  - s5
  - thumbhash
  - video
