name: cached_s5_video
description: Cached Video Provider for S5. Allows an application to take an S5 CID and display it with a simple, drop in, module.
repository: https://github.com/s5-dev/cached_s5_video
homepage: https://github.com/s5-dev/cached_s5_video

version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_s5_manager: ^1.2.1
  flutter:
    sdk: flutter
  flutter_thumbhash: ^0.1.0+1
  logger: ^2.4.0
  s5: ^0.2.0
  universal_io: ^2.2.2
  media_kit: any
  media_kit_video: any
  media_kit_libs_video: any
  media_kit_native_event_loop: any

# This is a fix for compiling on newer linux distros
# Will revert when mediakit updates pubdev
dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
      ref: main
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
      ref: main
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
      ref: main

  media_kit_native_event_loop:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_native_event_loop
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

topics:
  - cache
  - s5
  - thumbhash
  - video
